export const FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE";

export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const UPDATE_EDITOR_TEXT = "UPDATE_EDITOR_TEXT";
export const UPDATE_EDITOR_ERROR = "UPDATE_EDITOR_ERROR";
export const CLEAR_TEXT = "CLEAR_TEXT";

export const ADMIN_SIGN_IN_SUCCESS = "ADMIN_SIGN_IN_SUCCESS";
export const ADMIN_SIGN_IN_REQUEST = "ADMIN_SIGN_IN_REQUEST";
export const ADMIN_SIGN_IN_FAILURE = "ADMIN_SIGN_IN_FAILURE";

export const ADMIN_SIGN_OUT_SUCCESS = "ADMIN_SIGN_OUT_SUCCESS";
export const ADMIN_SIGN_OUT_REQUEST = "ADMIN_SIGN_OUT_REQUEST";
export const ADMIN_SIGN_OUT_FAILURE = "ADMIN_SIGN_OUT_FAILURE";
