export const FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE";

export const LOAD_PROJECT_COMMITS_REQUEST = "LOAD_PROJECT_COMMITS_REQUEST";
export const LOAD_PROJECT_COMMITS_SUCCESS = "LOAD_PROJECT_COMMITS_SUCCESS";
export const LOAD_PROJECT_COMMITS_FAILURE = "LOAD_PROJECT_COMMITS_FAILURE";

export const LOAD_PROJECT_LANGS_REQUEST = "LOAD_PROJECT_LANGS_REQUEST";
export const LOAD_PROJECT_LANGS_SUCCESS = "LOAD_PROJECT_LANGS_SUCCESS";
export const LOAD_PROJECT_LANGS_FAILURE = "LOAD_PROJECT_LANGS_FAILURE";
